include: package:effective_dart/analysis_options.yaml
# include: package:pedantic/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    public_member_api_docs: false